### ISSUE TITLE
gnome-shell with wayland freezing when hovering channel name

### ISSUE THREAD

**Issue by c0ldplasma** [Chatterino/chatterino2#1511]
**Describe the bug**
When hovering the element where the channel name is in (see screenshot) there is a 50% chance of the gnome-shell completely freezing. Mouse is then frozen and gnome does not react to any keyboard input anymore. Sometimes gnome comes back to life after some time, maybe 30 seconds, but sometimes only a hard reset helps. 
This bug only occurs on my new Lenovo ThinkPad L13 Yoga. I have the same OS on my desktop PC and it does not occur there. 

And yes this only happens with Chatterino on this particular element.

**To reproduce**
Hover over channel name element under Fedora 31 Gnome 3.34

**Screenshots**
https://imgur.com/3iGJqtB

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Fedora 31 GNOME 3.34

**Hardware**
Lenovo ThinkPad L13 Yoga - i5-10210U

**Additional information**
This bug goes in my top 10 of weirdest bugs.

**Workaround**
Always move the mouse around it Kappa

**Comment by c0ldplasma** [comment]
So I found out this only happens under Wayland. Xorg works fine.

**Comment by leon-richardt** [comment]
I could imagine this to be related to tooltip creation. How do other "tooltipped" elements (e.g. emote tooltips when enabled in the settings) behave? Can you observe a similar freeze there?

**Comment by c0ldplasma** [comment]
I tested this a little bit further. The tooltips are definitely not the problem. The emote tooltips work without any problems, even with image preview. Actually what I just found out is that the freeze is not caused by the whole Element, but only the lowest few Pixels of it. (Approximately red line here: https://imgur.com/70RhlEA ) Even the channel name tooltip works fine when the mouse is not touching the lower part of this element. I have no idea what could cause this.

**Comment by apa420** [comment]
I know what the issue is. When you hover the bar you get the tooltip. Problem is that the tooltip is in FRONT of the bar now, which means that the tooltip should dissapear. So it does that and then you're hovering the toolbar again. In X11 it causes a flickering effect. The problem is that the tooltip is created too early.

**Comment by c0ldplasma** [comment]
Just noticed that I used x11 on my desktop all the time...thats why it didn't happen there. Changed to wayland and now it also happens on my desktop.

**Comment by c0ldplasma** [comment]
This bug seems to be fixed with GNOME 3.36 (Fedora 32)

**Comment by c0ldplasma** [comment]
I was wrong. Its still happening, but much less frequently.

**Comment by fourtf** [comment]
I think this is fixed

**Comment by c0ldplasma** [comment]
Tested it again on a Ubuntu 20.10 VM with Wayland session (As said it only happens on wayland) and it still happens with version 2.2.2. It freezes for a couple of seconds (the tooltip does not appear) and then it crashes.
![UL0D1KNHlW](https://user-images.githubusercontent.com/14879514/94340835-17427580-0005-11eb-84ba-e1a2bf86edc8.gif)

**Comment by fourtf** [comment]
Should I open this again? I don't see this being fixed in the chatterino code.

**Comment by jacomaga** [comment]
It's not working on fedora 33, any fix to it? 
Gnome 3.38.5 Wayland.

**Comment by pajlada** [comment]
Would love to have some help from some actual wayland users as it's not the most commonly used platform

**Comment by sheybey** [comment]
I'm a little late to the party, gnome 43.1 on debian testing, but I can't reproduce this issue under wayland with chatterino running under either QTWayland or XWayland. Hovering over the red line c0ldplasma posted just hides the tooltip instead of crashing.

Pure speculation, of course, but I would bet this was a gnome or mutter bug rather than a chatterino bug if it crashed the entire shell session.

**Comment by pajlada** [comment]
Closing until we have confirmations of this still happening after v2.4.0, thank you @sheybey
