### ISSUE TITLE
Fails to run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [Chatterino/chatterino2#1604]
**Describe the bug**

Fails to run on Ubuntu xenial:

```
/run/firejail/appimage/.appimage-9136/usr/bin/chatterino: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /run/firejail/appimage/.appimage-9136/usr/bin/chatterino)

/run/firejail/appimage/.appimage-9136/usr/bin/chatterino: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-9136/usr/bin/../lib/libcrypto.so.1.1)

/run/firejail/appimage/.appimage-9136/usr/bin/chatterino: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9136/usr/bin/../lib/libpulsecommon-11.1.so)

/run/firejail/appimage/.appimage-9136/usr/bin/chatterino: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-9136/usr/bin/../lib/libsystemd.so.0)

/run/firejail/appimage/.appimage-9136/usr/bin/chatterino: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9136/usr/bin/../lib/libsystemd.so.0)
```

**Additional information**
All additional information can be found at https://github.com/AppImage/appimage.github.io/pull/1709, including a log file of the test run.

**Comment by fourtf** [comment]
AFAIK this should work now

**Comment by probonopd** [comment]
Unfortunately it still fails; did you try to run it e.g., on a xenial Live ISO?
