### ISSUE TITLE
Chatterino crashes on sway after ten minutes

### ISSUE THREAD

**Issue by jeLee6gi** [Chatterino/chatterino2#2063]
**Describe the bug**
Chatterino terminates after ten minutes with `SIGABRT` and the following error message

```
The Wayland connection broke. Did the Wayland compositor die?
```

**To reproduce**

Run chatterino and wait for ten minutes

**Screenshots**

**Chatterino version**

Chatterino 2.2.2 (commit b67e20d96)

**Operating system**
Archlinux with sway 1.5 and wayland 1.18.0

**Additional information**

**Comment by alazymeme** [comment]
@leon-richardt You have crashing issues with sway as well? I think I remember you mentioning it.

**Comment by leon-richardt** [comment]
Yes, see #1955, crashes still occur.
Behavior is different for me though. Definitely not related to time but rather opening links (so most likely some communication problem between sway and `QDesktopServices`).

**Comment by jeLee6gi** [comment]
Interesting, for me chatterino consistently closes after ten minutes but I can open links just fine. Is there a way for me to get more verbose logging output?

**Comment by leon-richardt** [comment]
> Interesting, for me chatterino consistently closes after ten minutes but I can open links just fine. Is there a way for me to get more verbose logging output?

You can try running Chatterino with `export QT_DEBUG_PLUGINS=1` as outlined in https://github.com/Chatterino/chatterino2/issues/1779#issuecomment-653770705.

**Comment by jeLee6gi** [comment]
Hm, Heisenbug. I'll need to test more how it occurs in a couple of hours. Thank you already for your help and time, I'll report back soon.

**Comment by leon-richardt** [comment]
@jeLee6gi
Hey, just wondering whether you still observe this after sway version 1.5.1. My problem with it (#1955) seems to have been party fixed by the update :)

**Comment by jeLee6gi** [comment]
I'm still getting the same crashes in sway 1.5.1. I wasn't able to debug it, sometimes I get `SIGABRT`, sometimes it dumps core. The only thing I can say for sure is that it doesn't happen when I don't have any splits/channels open and I guess redraws don't really occur.

Here is one of the core dumps

```
systemd-coredump[166934]: Process 164219 (chatterino) of user 1000 dumped core.
                                               
                                               Stack trace of thread 164219:
                                               #0  0x00007fa986a2c615 raise (libc.so.6 + 0x3d615)
                                               #1  0x00007fa986a15862 abort (libc.so.6 + 0x26862)
                                               #2  0x00007fa986fa99ac _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0x909ac)
                                               #3  0x00007fa9827710fa n/a (libQt5WaylandClient.so.5 + 0x610fa)
                                               #4  0x00007fa98277643a _ZN15QtWaylandClient23QWaylandShmBackingStore6resizeERK5QSize (libQt5WaylandClient.so.5 + 0x6643a)
                                               #5  0x00007fa98277669a _ZN15QtWaylandClient23QWaylandShmBackingStore10beginPaintERK7QRegion (libQt5WaylandClient.so.5 + 0x6669a)
                                               #6  0x00007fa987974673 _ZN13QBackingStore10beginPaintERK7QRegion (libQt5Gui.so.5 + 0x302673)
                                               #7  0x00007fa987fbb142 n/a (libQt5Widgets.so.5 + 0x16b142)
                                               #8  0x00007fa987fec25b _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5 + 0x19c25b)
                                               #9  0x00007fa987faa752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15a752)
                                               #10 0x00007fa9871cccda _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b3cda)
                                               #11 0x00007fa9871cf7d3 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2b67d3)
                                               #12 0x00007fa987226304 n/a (libQt5Core.so.5 + 0x30d304)
                                               #13 0x00007fa9888a4914 g_main_context_dispatch (libglib-2.0.so.0 + 0x52914)
                                               #14 0x00007fa9888f87d1 n/a (libglib-2.0.so.0 + 0xa67d1)
                                               #15 0x00007fa9888a3121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                                               #16 0x00007fa987225941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                                               #17 0x00007fa9871cb65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                                               #18 0x00007fa9871d3af4 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2baaf4)
                                               #19 0x0000558c8dbdffd2 n/a (chatterino + 0x2d3fd2)
                                               #20 0x0000558c8d9c741c main (chatterino + 0xbb41c)
                                               #21 0x00007fa986a17152 __libc_start_main (libc.so.6 + 0x28152)
                                               #22 0x0000558c8d9eca0e n/a (chatterino + 0xe0a0e)
                                               
                                               Stack trace of thread 164220:
                                               #0  0x00007fa986ae446f __poll (libc.so.6 + 0xf546f)
                                               #1  0x00007fa9888f875f n/a (libglib-2.0.so.0 + 0xa675f)
                                               #2  0x00007fa9888a3121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                                               #3  0x00007fa987225941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                                               #4  0x00007fa9871cb65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                                               #5  0x00007fa986fe5ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                                               #6  0x00007fa986fe6e8f n/a (libQt5Core.so.5 + 0xcde8f)
                                               #7  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #8  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164229:
                                               #0  0x00007fa986ae446f __poll (libc.so.6 + 0xf546f)
                                               #1  0x00007fa9888f875f n/a (libglib-2.0.so.0 + 0xa675f)
                                               #2  0x00007fa9888a3121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                                               #3  0x00007fa98722595c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c95c)
                                               #4  0x00007fa9871cb65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                                               #5  0x00007fa986fe5ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                                               #6  0x00007fa986fe6e8f n/a (libQt5Core.so.5 + 0xcde8f)
                                               #7  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #8  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164221:
                                               #0  0x00007fa986ae446f __poll (libc.so.6 + 0xf546f)
                                               #1  0x00007fa9888f875f n/a (libglib-2.0.so.0 + 0xa675f)
                                               #2  0x00007fa9888a3121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                                               #3  0x00007fa987225941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                                               #4  0x00007fa9871cb65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                                               #5  0x00007fa986fe5ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                                               #6  0x00007fa987482098 n/a (libQt5DBus.so.5 + 0x17098)
                                               #7  0x00007fa986fe6e8f n/a (libQt5Core.so.5 + 0xcde8f)
                                               #8  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #9  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164227:
                                               #0  0x00007fa986ae446f __poll (libc.so.6 + 0xf546f)
                                               #1  0x00007fa9888f875f n/a (libglib-2.0.so.0 + 0xa675f)
                                               #2  0x00007fa9888a3121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                                               #3  0x00007fa987225941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                                               #4  0x00007fa9871cb65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                                               #5  0x00007fa986fe5ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                                               #6  0x00007fa986fe6e8f n/a (libQt5Core.so.5 + 0xcde8f)
                                               #7  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #8  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164232:
                                               #0  0x00007fa986f066a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                               #1  0x00007fa956dad8dc n/a (iris_dri.so + 0x4d28dc)
                                               #2  0x00007fa956dad7d8 n/a (iris_dri.so + 0x4d27d8)
                                               #3  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #4  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164228:
                                               #0  0x00007fa986f066a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                               #1  0x0000558c8db50c43 n/a (chatterino + 0x244c43)
                                               #2  0x0000558c8db39c52 n/a (chatterino + 0x22dc52)
                                               #3  0x0000558c8db52b68 n/a (chatterino + 0x246b68)
                                               #4  0x0000558c8db45c20 n/a (chatterino + 0x239c20)
                                               #5  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #6  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164237:
                                               #0  0x00007fa986aef5de epoll_wait (libc.so.6 + 0x1005de)
                                               #1  0x0000558c8db4ec28 n/a (chatterino + 0x242c28)
                                               #2  0x0000558c8db50a1b n/a (chatterino + 0x244a1b)
                                               #3  0x0000558c8db39c52 n/a (chatterino + 0x22dc52)
                                               #4  0x0000558c8db3a0df n/a (chatterino + 0x22e0df)
                                               #5  0x00007fa986de7c24 execute_native_thread_routine (libstdc++.so.6 + 0xcfc24)
                                               #6  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #7  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 166757:
                                               #0  0x00007fa986f069c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                                               #1  0x00007fa986fed058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                                               #2  0x00007fa986feafc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                                               #3  0x00007fa986fe6e8f n/a (libQt5Core.so.5 + 0xcde8f)
                                               #4  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #5  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164234:
                                               #0  0x00007fa986f066a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                               #1  0x00007fa956dad8dc n/a (iris_dri.so + 0x4d28dc)
                                               #2  0x00007fa956dad7d8 n/a (iris_dri.so + 0x4d27d8)
                                               #3  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #4  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164233:
                                               #0  0x00007fa986f066a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                               #1  0x00007fa956dad8dc n/a (iris_dri.so + 0x4d28dc)
                                               #2  0x00007fa956dad7d8 n/a (iris_dri.so + 0x4d27d8)
                                               #3  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #4  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
                                               
                                               Stack trace of thread 164231:
                                               #0  0x00007fa986f066a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                               #1  0x00007fa956dad8dc n/a (iris_dri.so + 0x4d28dc)
                                               #2  0x00007fa956dad7d8 n/a (iris_dri.so + 0x4d27d8)
                                               #3  0x00007fa986f003e9 start_thread (libpthread.so.0 + 0x93e9)
                                               #4  0x00007fa986aef293 __clone (libc.so.6 + 0x100293)
```

**Comment by jeLee6gi** [comment]
A couple of system upgrades later the problem has vanished.

I don't know what fixed it, but I am running these versions now:

Chatterino 2.2.3-beta2 (commit 155b40985)
sway 1.5.1
wlroots 0.12

Thank you everyone for your help!
