### ISSUE TITLE
Combos feature

### ISSUE THREAD

**Issue by gapbl4** [Chatterino/chatterino2#892]
Would be great to have optional combo feature that would replace multiple lines of identical emotes/messages with a single line, i.e. :

![gachigasm](https://user-images.githubusercontent.com/14076068/49335422-36853d00-f5fe-11e8-9a27-208323c142f1.png) x69 Combo

or something similar to make spammy chats a bit more readable.

**Comment by hemirt** [comment]
Would be nice to get rid off either mod spam or multiple people spamming the same thing (albeit with some small differences, eg. a dot at the end, numbers, etc...)

Also would be better to be only able to enable it on longer (than x characters) messages

Or have it be more strict (adjustable) for shorter messages (aka one emote spam)

Levenshtein distance sounds nice
> The Levenshtein distance has several simple upper and lower bounds. These include:
> - It is at least the difference of the sizes of the two strings.
> - It is at most the length of the longer string.
> - It is zero if and only if the strings are equal.
> - If the strings are the same size, the Hamming distance is an upper bound on the Levenshtein distance.
> - The Levenshtein distance between two strings is no greater than the sum of their Levenshtein distances from a third string (triangle inequality).

https://en.wikipedia.org/wiki/Levenshtein_distance

The Damerau-Levenshtein distance also allows transposition of two adjacent characters, so that might be better

https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance

**Comment by alazymeme** [comment]
Would you say this was solved by https://github.com/Chatterino/chatterino2/pull/1496?

**Comment by apa420** [comment]
Fixed by #1496

**Comment by doximanman** [comment]
I would also like this to be a feature. #1496 doesn't solve this. It hides similar messages from the same person.
What this is suggesting is to combine any number of consecutive emote messages into one combo message. for instance:
someone: LULW
someone else: LULW
another person: LULW

would be shown as:
LULW x3 combo
And the individual messages wouldn't be shown.
